import { MenuItem, Category, DayHours } from "./types";

export const CATEGORIES: Category[] = [
  { id: "pizze-rosse", name: "PIZZE ROSSE" },
  { id: "pizze-bianche", name: "PIZZE BIANCHE" },
  { id: "pizze-speciali", name: "PIZZE SPECIALI" },
  { id: "focacce", name: "FOCACCE" },
  { id: "calzoni", name: "CALZONI" },
  { id: "stuzzicheria", name: "STUZZICHERIA" },
  { id: "antipasti", name: "ANTIPASTI" },
  { id: "primi", name: "PRIMI" },
  { id: "secondi", name: "SECONDI" },
  { id: "dolci", name: "DOLCI" },
  { id: "bevande", name: "BEVANDE AL TAVOLO" },
  { id: "senza-glutine", name: "SENZA GLUTINE" },
];

export const MENU_ITEMS: MenuItem[] = [
  // FOCACCE
  {
    id: "foc1",
    name: "FOCACCIA",
    price: 4.0,
    ingredients: "Olio, sale, rosmarino",
    category: "focacce",
  },
  {
    id: "foc2",
    name: "CIPOLLATA",
    price: 6.0,
    ingredients: "Olio, sale, rosmarino",
    category: "focacce",
  },
  {
    id: "foc3",
    name: "FOCACCIA ALICI",
    price: 7.5,
    ingredients: "Olio, alici, pachino, rosmarino, origano",
    category: "focacce",
  },
  {
    id: "foc4",
    name: "FOCACCIA PROSCIUTTO CRUDO",
    price: 7.5,
    ingredients: "Olio, sale, prosciutto crudo",
    category: "focacce",
  },
  {
    id: "foc5",
    name: "CAPRESE",
    price: 7.0,
    ingredients: "Mozzarella fresca, pomodoro a fette, basilico",
    category: "focacce",
    isVegetarian: true,
  },

  // PIZZE BIANCHE
  {
    id: "pb1",
    name: "BOSCAIOLA",
    price: 8.5,
    ingredients: "Mozzarella, prosciutto cotto, funghi",
    category: "pizze-bianche",
  },
  {
    id: "pb2",
    name: "CAMPAGNOLA",
    price: 8.5,
    ingredients: "Mozzarella, prosciutto crudo",
    category: "pizze-bianche",
  },
  {
    id: "pb3",
    name: "CIME E SALSICCIA",
    price: 8.5,
    ingredients: "Mozzarella, salsiccia, cime di rapa",
    category: "pizze-bianche",
  },
  {
    id: "pb4",
    name: "GIRASOLE",
    price: 8.5,
    ingredients: "Mozzarella, prosciutto cotto, mais",
    category: "pizze-bianche",
  },
  {
    id: "pb5",
    name: "MARCHIONNI",
    price: 9.0,
    ingredients: "Mozzarella, prosciutto cotto, carciofi",
    category: "pizze-bianche",
  },
  {
    id: "pb6",
    name: "MALIZIA",
    price: 8.5,
    ingredients: "Mozzarella, salsiccia, peperoni",
    category: "pizze-bianche",
  },
  {
    id: "pb7",
    name: "PATTY",
    price: 8.5,
    ingredients: "Mozzarella, salsiccia, patate",
    category: "pizze-bianche",
  },
  {
    id: "pb8",
    name: "4 FORMAGGI",
    price: 9.0,
    ingredients: "Mozzarella, emmental, parmigiano, gorgonzola",
    category: "pizze-bianche",
    isVegetarian: true,
  },
  {
    id: "pb9",
    name: "RADICCHIO E GORGONZOLA",
    price: 8.5,
    ingredients: "Mozzarella, radicchio, gorgonzola",
    category: "pizze-bianche",
    isVegetarian: true,
  },
  {
    id: "pb10",
    name: "RADICCHIO E SPECK",
    price: 9.0,
    ingredients: "Mozzarella, radicchio, speck",
    category: "pizze-bianche",
  },
  {
    id: "pb11",
    name: "RUCOLA",
    price: 8.5,
    ingredients: "Mozzarella, rucola, scaglie di parmigiano Regg.",
    category: "pizze-bianche",
    isVegetarian: true,
  },
  {
    id: "pb12",
    name: "RUSTICA",
    price: 9.0,
    ingredients: "Mozzarella, salsiccia, funghi, parmigiano Regg.",
    category: "pizze-bianche",
  },
  {
    id: "pb13",
    name: "VEGETARIANA",
    price: 9.0,
    ingredients: "Mozzarella, verdure",
    category: "pizze-bianche",
    isVegetarian: true,
  },
  {
    id: "pb14",
    name: "ZUCCHINE",
    price: 7.5,
    ingredients: "Mozzarella, zucchine",
    category: "pizze-bianche",
    isVegetarian: true,
  },

  // CALZONI
  {
    id: "cal1",
    name: "CALZONE PROSCIUTTO COTTO",
    price: 8.5,
    ingredients: "Mozzarella, prosciutto cotto",
    category: "calzoni",
  },
  {
    id: "cal2",
    name: "CALZONE CLASSICO",
    price: 9.0,
    ingredients: "Mozzarella, prosciutto cotto, funghi",
    category: "calzoni",
  },
  {
    id: "cal3",
    name: "CALZONE SALAME",
    price: 9.0,
    ingredients: "Mozzarella, salame piccante, carciofi",
    category: "calzoni",
  },
  {
    id: "cal4",
    name: "CALZONE RICOTTA",
    price: 9.0,
    ingredients: "Ricotta, prosciutto cotto, basilico, parm. Regg.",
    category: "calzoni",
  },

  // PIZZE ROSSE
  {
    id: "pr1",
    name: "MARINARA",
    price: 5.5,
    ingredients: "Pomodoro, origano, aglio",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr2",
    name: "MARGHERITA",
    price: 6.5,
    ingredients: "Pomodoro, mozzarella",
    category: "pizze-rosse",
    isVegetarian: true,
    isBestSeller: true,
  },
  {
    id: "pr3",
    name: "AMERICANA",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, salame piccante, peperoni",
    category: "pizze-rosse",
    isSpicy: true,
  },
  {
    id: "pr4",
    name: "CARCIOFI",
    price: 8.5,
    ingredients: "Pomodoro, mozzarella, carciofi",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr5",
    name: "CAPRICCIOSA",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, p. cotto, carciofi, funghi, olive",
    category: "pizze-rosse",
  },
  {
    id: "pr6",
    name: "4 STAGIONI",
    price: 9.0,
    ingredients: "Pom., mozzarella, 1/3 funghi, 1/3 p.cotto, 1/3carciofi",
    category: "pizze-rosse",
  },
  {
    id: "pr7",
    name: "DIAVOLA",
    price: 8.5,
    ingredients: "Pomodoro, mozzarella, salame piccante",
    category: "pizze-rosse",
    isSpicy: true,
  },
  {
    id: "pr8",
    name: "FUNGHI",
    price: 8.0,
    ingredients: "Pomodoro, mozzarella, funghi",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr9",
    name: "GORGONZOLA",
    price: 8.0,
    ingredients: "Pomodoro, mozzarella, gorgonzola",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr10",
    name: "MELANZANE",
    price: 8.0,
    ingredients: "Pomodoro, mozzarella, melanzane",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr11",
    name: "NAPOLETANA",
    price: 8.5,
    ingredients: "Pomodoro, mozzarella, alici, capperi",
    category: "pizze-rosse",
  },
  {
    id: "pr12",
    name: "PEPERONI",
    price: 8.0,
    ingredients: "Pomodoro, mozzarella, peperoni",
    category: "pizze-rosse",
    isVegetarian: true,
  },
  {
    id: "pr13",
    name: "PROSCIUTTO COTTO",
    price: 8.5,
    ingredients: "Pomodoro, mozzarella, prosciutto cotto",
    category: "pizze-rosse",
  },
  {
    id: "pr14",
    name: "PROSCIUTTO E FUNGHI",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, p. cotto, funghi",
    category: "pizze-rosse",
  },
  {
    id: "pr15",
    name: "PUGLIESE",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, tonno, cipolla",
    category: "pizze-rosse",
  },
  {
    id: "pr16",
    name: "ROMANA",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, alici, capperi, olive",
    category: "pizze-rosse",
  },
  {
    id: "pr17",
    name: "SALSICCIA",
    price: 8.5,
    ingredients: "Pomodoro, mozzarella, salsiccia",
    category: "pizze-rosse",
  },
  {
    id: "pr18",
    name: "VIENNESE",
    price: 8.0,
    ingredients: "Pomodoro, mozzarella, wurstel",
    category: "pizze-rosse",
  },

  // PIZZE SPECIALI
  {
    id: "spec1",
    name: "AMATRICIANA",
    price: 9.0,
    ingredients: "Mozzarella, pachino, pancetta, parmigiano",
    category: "pizze-speciali",
  },
  {
    id: "spec2",
    name: "BRESAOLA",
    price: 9.5,
    ingredients: "Mozzarella, bresaola, rucola, scaglie di parmigiano",
    category: "pizze-speciali",
  },
  {
    id: "spec3",
    name: "BUFALINA",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella di bufala, basilico",
    category: "pizze-speciali",
    isVegetarian: true,
    isBestSeller: true,
  },
  {
    id: "spec4",
    name: "CONTADINA",
    price: 9.0,
    ingredients: "Mozzarella, pomodoro a fette, prosciutto crudo",
    category: "pizze-speciali",
  },
  {
    id: "spec5",
    name: "COCKTAIL",
    price: 9.0,
    ingredients: "Pomodoro, gamberetti, salsa rosa, rucola",
    category: "pizze-speciali",
  },
  {
    id: "spec6",
    name: "DOC",
    price: 10.0,
    ingredients: "Mozzarella di bufala, pachino, basilico",
    category: "pizze-speciali",
    isVegetarian: true,
  },
  {
    id: "spec7",
    name: "DORA",
    price: 10.0,
    ingredients: "Mozzarella, funghi, patate, scamorza, p. crudo",
    category: "pizze-speciali",
  },
  {
    id: "spec8",
    name: "ESTIVA",
    price: 10.0,
    ingredients: "Mozzarella, pachino, rucola, parmigiano, bufala",
    category: "pizze-speciali",
    isVegetarian: true,
    isBestSeller: true,
  },
  {
    id: "spec9",
    name: "ITALIA",
    price: 9.0,
    ingredients: "Mozzarella, pachino, rucola, parmigiano",
    category: "pizze-speciali",
    isVegetarian: true,
  },
  {
    id: "spec10",
    name: "LA BOMBA",
    price: 9.5,
    ingredients: "Pomodoro, mozzarella, salame picc., peperoni, gorgonzola",
    category: "pizze-speciali",
  },
  {
    id: "spec11",
    name: "MAURO",
    price: 10.0,
    ingredients: "Pomodoro, mozzarella, salsiccia, cipolla, peperoni, gorgonzola",
    category: "pizze-speciali",
  },
  {
    id: "spec12",
    name: "MESSICANA",
    price: 9.5,
    ingredients: "Pomodoro, mozzarella, salame picc., pancetta, gorgonzola",
    category: "pizze-speciali",
  },
  {
    id: "spec13",
    name: "MAESTRO PICCANTE",
    price: 9.0,
    ingredients: "Pom., mozz. di bufala, pachino, rucola, picc.",
    category: "pizze-speciali",
  },
  {
    id: "spec14",
    name: "MAESTRO CRUDO",
    price: 10.0,
    ingredients: "Pom., mozz. di bufala, pachino, p. crudo",
    category: "pizze-speciali",
  },
  {
    id: "spec15",
    name: "MAESTRO COTTO",
    price: 9.0,
    ingredients: "Pom., mozz. di bufala, pachino, p. cotto",
    category: "pizze-speciali",
  },
  {
    id: "spec16",
    name: "NORDICA",
    price: 9.5,
    ingredients: "Mozzarella, radicchio, gorgonzola, speck",
    category: "pizze-speciali",
  },
  {
    id: "spec17",
    name: "NORCINA",
    price: 9.5,
    ingredients: "Mozzarella, porcini, tartufo, salsiccia",
    category: "pizze-speciali",
  },
  {
    id: "spec18",
    name: "PARMIGIANA",
    price: 9.0,
    ingredients: "Pomodoro, mozzarella, melanzane, parmigiano",
    category: "pizze-speciali",
    isVegetarian: true,
  },
  {
    id: "spec19",
    name: "PERMALOSA",
    price: 9.5,
    ingredients: "Mozzarella, pachino, porcini, parmigiano",
    category: "pizze-speciali",
  },
  {
    id: "spec20",
    name: "PISTACCHIO",
    price: 9.5,
    ingredients: "Mozzarella, pistacchio, mortadella",
    category: "pizze-speciali",
  },
  {
    id: "spec21",
    name: "PIETRO",
    price: 9.0,
    ingredients: "Mozzarella, stracchino, funghi, pachino, rucola",
    category: "pizze-speciali",
  },
  {
    id: "spec22",
    name: "STRACCHINO",
    price: 10.0,
    ingredients: "Mozzarella, stracchino, rucola, prosciutto crudo",
    category: "pizze-speciali",
  },
  {
    id: "spec23",
    name: "SPECIAL",
    price: 10.0,
    ingredients: "Pomodoro, mozzarella, funghi, carciofi, speck",
    category: "pizze-speciali",
  },
  {
    id: "spec24",
    name: "STRONG",
    price: 9.5,
    ingredients: "Mozzarella, tonno, olive, capperi, peperoncino",
    category: "pizze-speciali",
  },
  {
    id: "spec25",
    name: "SUPER",
    price: 10.0,
    ingredients: "Pomodoro, mozzarella, porcini, tartufo, speck",
    category: "pizze-speciali",
  },
  {
    id: "spec26",
    name: "TARTUFATA",
    price: 9.0,
    ingredients: "Mozzarella, porcini, tartufo, parmigiano",
    category: "pizze-speciali",
  },
  {
    id: "spec27",
    name: "TIROLESE",
    price: 9.0,
    ingredients: "Mozzarella, funghi, scamorza, speck",
    category: "pizze-speciali",
  },

  // STUZZICHERIA
  {
    id: "st1",
    name: "PATATINE FRITTE",
    price: 4.0,
    ingredients: "",
    category: "stuzzicheria",
  },
  {
    id: "st2",
    name: "CHIPS",
    price: 4.0,
    ingredients: "FATTE DA NOI",
    category: "stuzzicheria",
  },
  {
    id: "st3",
    name: "ZUCCHINE FRITTE",
    price: 4.0,
    ingredients: "",
    category: "stuzzicheria",
  },
  {
    id: "st4",
    name: "MOZZARELLINE FRITTE",
    price: 4.0,
    ingredients: "8 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st5",
    name: "OLIVE ALL’ASOLANA",
    price: 4.5,
    ingredients: "7 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st6",
    name: "SUPLI",
    price: 4.0,
    ingredients: "3 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st7",
    name: "CROCCHETTE DI POLLO",
    price: 4.0,
    ingredients: "7 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st8",
    name: "CROCCHETTE DI PATATE FATTE DA NOI",
    price: 4.0,
    ingredients: "3 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st9",
    name: "FRITTATINE di pasta FATTE DA NOI",
    price: 4.0,
    ingredients: "3 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st10",
    name: "PANZEROTTO FRITTO",
    price: 4.0,
    ingredients: "calzone con cotto e mozzarella",
    category: "stuzzicheria",
  },
  {
    id: "st11",
    name: "FRITTELLE",
    price: 3.0,
    ingredients: "4 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st12",
    name: "FRITTELLE ALICI",
    price: 5.0,
    ingredients: "4 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st13",
    name: "FRITTELLE CRUDO",
    price: 5.0,
    ingredients: "4 pz.",
    category: "stuzzicheria",
  },
  {
    id: "st14",
    name: "FORMAGGIO FRITTO FATTE DA NOI",
    price: 4.5,
    ingredients: "3 pz.",
    category: "stuzzicheria",
  },

  // ANTIPASTI
  {
    id: "ant1",
    name: "BRUSCHETTA POMODORO",
    price: 3.0,
    ingredients: "3 pz.",
    category: "antipasti",
  },
  {
    id: "ant2",
    name: "BRUSCHETTA MISTA",
    price: 4.5,
    ingredients: "3 pz.",
    category: "antipasti",
  },
  {
    id: "ant3",
    name: "CROSTINO Mozzarella e prosciutto crudo",
    price: 4.5,
    ingredients: "3 pz.",
    category: "antipasti",
  },
  {
    id: "ant4",
    name: "AFFETTATO MISTO",
    price: 9.0,
    ingredients: "Con focacce",
    category: "antipasti",
  },
  {
    id: "ant5",
    name: "AFFETTATO PROSCIUTTO CRUDO CON FRITTELLA",
    price: 9.5,
    ingredients: "",
    category: "antipasti",
  },
  {
    id: "ant6",
    name: "ANTIPASTO DELLA CASA",
    price: 25.0,
    ingredients: "Affettato misto con bruschette, formaggio, oliva ascolana, crocchetta di patate, frittelle (per 2 persone)",
    category: "antipasti",
  },
  {
    id: "ant7",
    name: "BRESAOLA IN CARPACCIO",
    price: 8.0,
    ingredients: "Affettato bresaola, rucola, parmigiano",
    category: "antipasti",
  },
  {
    id: "ant8",
    name: "CAPRESE AL PIATTO",
    price: 8.0,
    ingredients: "Mozzarella, pomodoro a fette, basilico",
    category: "antipasti",
    isVegetarian: true,
  },
  {
    id: "ant9",
    name: "INSALATONA",
    price: "S.Q.",
    ingredients: "A vostro gusto",
    category: "antipasti",
  },

  // PRIMI
  {
    id: "prm1",
    name: "LASAGNA",
    price: 9.0,
    ingredients: "",
    category: "primi",
  },
  {
    id: "prm2",
    name: "CANNELLONI",
    price: 9.0,
    ingredients: "",
    category: "primi",
  },
  {
    id: "prm3",
    name: "PARMIGIANA",
    price: 9.0,
    ingredients: "",
    category: "primi",
  },
  {
    id: "prm4",
    name: "PRIMO DEL GIORNO",
    price: "S.Q.",
    ingredients: "",
    category: "primi",
  },

  // SECONDI
  {
    id: "sec1",
    name: "COTOLETTA DI POLLO",
    price: 9.0,
    ingredients: "Con insalata o patate al forno o patate fritte",
    category: "secondi",
  },
  {
    id: "sec2",
    name: "HAMBURGER ALPIATTO",
    price: 10.0,
    ingredients: "Con insalata o patate al forno o patate fritte",
    category: "secondi",
  },
  {
    id: "sec3",
    name: "TAGLIATA DI POLLO",
    price: 9.0,
    ingredients: "Con rucola e scaglie di parmigiano",
    category: "secondi",
  },
  {
    id: "sec4",
    name: "SCALOPPINA DI POLLO",
    price: 8.0,
    ingredients: "Al limone o al vino bianco",
    category: "secondi",
  },

  // DOLCI
  {
    id: "dol1",
    name: "TIRAMISU",
    price: 5.0,
    ingredients: "",
    category: "dolci",
  },
  {
    id: "dol2",
    name: "PROFITEROLES",
    price: 4.0,
    ingredients: "",
    category: "dolci",
  },
  {
    id: "dol3",
    name: "TARTUFO BIANCO",
    price: 4.5,
    ingredients: "Gelato",
    category: "dolci",
  },
  {
    id: "dol4",
    name: "CREMA CATALANA",
    price: 4.0,
    ingredients: "",
    category: "dolci",
  },
  {
    id: "dol5",
    name: "PANNA COTTA A",
    price: 4.0,
    ingredients: "FRUTTI DI BOSCO o CARAMELLO o NUTELLA",
    category: "dolci",
  },
  {
    id: "dol6",
    name: "MILLE FOGLIE CON CREMA e",
    price: 5.0,
    ingredients: "FRAGOLA o PISTACCHIO o NUTELLA",
    category: "dolci",
  },
  {
    id: "dol7",
    name: "DOLCE DEL GIORNO",
    price: 4.0,
    ingredients: "",
    category: "dolci",
  },

  // BEVANDE AL TAVOLO
  {
    id: "bev1",
    name: "TE AL LIMONE / PESCA",
    price: 2.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev2",
    name: "COCA-COLA vetro",
    price: 3.0,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev3",
    name: "COCA-COLA vetro",
    price: 5.0,
    ingredients: "1.00 Lt",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev4",
    name: "COCA-COLA, FANTA, SPRITE lattina",
    price: 2.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev5",
    name: "SCHWEPPES TONICA / LIMONE",
    price: 2.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev6",
    name: "APEROL SPRITZ",
    price: 5.0,
    ingredients: "",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev7",
    name: "ACQUA naturale / frizzante",
    price: 1.5,
    ingredients: "50 cl",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },
  {
    id: "bev8",
    name: "ACQUA naturale / frizzante",
    price: 2.5,
    ingredients: "1.00 Lt",
    category: "bevande",
    subcategory: "BEVANDE AL TAVOLO",
  },

  // BIRRE
  {
    id: "bir1",
    name: "CORONA",
    price: 4.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir2",
    name: "CERES",
    price: 4.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir3",
    name: "ICHNUSA",
    price: 4.0,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir4",
    name: "ICHNUSA NON FILTRATA",
    price: 4.0,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir5",
    name: "BECK’S",
    price: 3.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir6",
    name: "SUPER TENNENT’S",
    price: 4.5,
    ingredients: "33 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },
  {
    id: "bir7",
    name: "MORETTI",
    price: 5.0,
    ingredients: "66 cl",
    category: "bevande",
    subcategory: "BIRRE",
  },

  // BIRRE ALLA SPINA
  {
    id: "bps1",
    name: "MORETTI BAFFO D’ORO",
    price: 3.0,
    ingredients: "20 cl",
    category: "bevande",
    subcategory: "BIRRE ALLA SPINA",
  },
  {
    id: "bps2",
    name: "MORETTI BAFFO D’ORO",
    price: 5.0,
    ingredients: "40 cl",
    category: "bevande",
    subcategory: "BIRRE ALLA SPINA",
  },
  {
    id: "bps3",
    name: "IKNUSA NON FILTRATA",
    price: 3.0,
    ingredients: "20 cl",
    category: "bevande",
    subcategory: "BIRRE ALLA SPINA",
  },
  {
    id: "bps4",
    name: "IKNUSA NON FILTRATA",
    price: 5.0,
    ingredients: "40 cl",
    category: "bevande",
    subcategory: "BIRRE ALLA SPINA",
  },

  // VINO ROSSO / BIANCO Cantina Carminucci
  {
    id: "vcc1",
    name: "VINO ROSSO / BIANCO Cantina Carminucci",
    price: 2.0,
    ingredients: "25 cl",
    category: "bevande",
    subcategory: "VINO ROSSO / BIANCO Cantina Carminucci",
  },
  {
    id: "vcc2",
    name: "VINO ROSSO / BIANCO Cantina Carminucci",
    price: 4.0,
    ingredients: "50 cl",
    category: "bevande",
    subcategory: "VINO ROSSO / BIANCO Cantina Carminucci",
  },
  {
    id: "vcc3",
    name: "VINO ROSSO / BIANCO Cantina Carminucci",
    price: 7.0,
    ingredients: "1.00 Lt",
    category: "bevande",
    subcategory: "VINO ROSSO / BIANCO Cantina Carminucci",
  },

  // VINO IN BOTTIGLIA ROSSO CANTINA CARMINUCCI
  {
    id: "vbr1",
    name: "GROTTE SUL MARE Rosso Piceno DOC",
    price: 15.0,
    ingredients: "",
    category: "bevande",
    subcategory: "VINO IN BOTTIGLIA ROSSO CANTINA CARMINUCCI",
  },
  {
    id: "vbr2",
    name: "NAUMAKOS Rosso Piceno Superiore",
    price: 18.0,
    ingredients: "",
    category: "bevande",
    subcategory: "VINO IN BOTTIGLIA ROSSO CANTINA CARMINUCCI",
  },

  // VINO IN BOTTIGLIA BIANCO CANTINA CARMINUCCI
  {
    id: "vbb1",
    name: "CASTA PASSERINA Marche IGP",
    price: 15.0,
    ingredients: "",
    category: "bevande",
    subcategory: "VINO IN BOTTIGLIA BIANCO CANTINA CARMINUCCI",
  },
  {
    id: "vbb2",
    name: "BELATO OFFIDA PECORINO",
    price: 18.0,
    ingredients: "",
    category: "bevande",
    subcategory: "VINO IN BOTTIGLIA BIANCO CANTINA CARMINUCCI",
  },

  // LIQUORI
  {
    id: "liq1",
    name: "AMARO DEL CAPO",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq2",
    name: "LIQUIRIZIA",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq3",
    name: "BRANCA MENTA",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq4",
    name: "FERNET BRANCA",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq5",
    name: "MONTENEGRO",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq6",
    name: "SAMBUCA",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq7",
    name: "JAGERMEISSTER",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq8",
    name: "GRAPPA",
    price: 3.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq9",
    name: "LIMONCELLO",
    price: 2.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq10",
    name: "GENZIANA",
    price: 2.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq11",
    name: "WHISKY",
    price: 5.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },
  {
    id: "liq12",
    name: "RUM",
    price: 5.0,
    ingredients: "",
    category: "bevande",
    subcategory: "LIQUORI",
  },

  // PRODOTTI SENZA GLUTINE
  {
    id: "sg1",
    name: "PIZZE",
    price: "+ € 2.50",
    ingredients: "Qualsiasi pizza dal menu con la correzione",
    category: "senza-glutine",
    isGlutenFree: true,
  },
  {
    id: "sg2",
    name: "PATATINE FRITTE",
    price: 4.0,
    ingredients: "",
    category: "senza-glutine",
    isGlutenFree: true,
  },
  {
    id: "sg3",
    name: "OLIVE ALL’ASOLANA",
    price: 5.0,
    ingredients: "7 pz.",
    category: "senza-glutine",
    isGlutenFree: true,
  },
  {
    id: "sg4",
    name: "CROCCHETTE DI POLLO",
    price: 5.0,
    ingredients: "5 pz.",
    category: "senza-glutine",
    isGlutenFree: true,
  },
  {
    id: "sg5",
    name: "TIRAMISU",
    price: 5.0,
    ingredients: "",
    category: "senza-glutine",
    isGlutenFree: true,
  },
];

export const OPENING_HOURS: DayHours[] = [
  { day: "Lunedì", hours: "18:30 - 23:00", isOpen: true, openTime: "18:30", closeTime: "23:00" },
  { day: "Martedì", hours: "18:30 - 23:00", isOpen: true, openTime: "18:30", closeTime: "23:00" },
  { day: "Mercoledì", hours: "18:30 - 23:00", isOpen: true, openTime: "18:30", closeTime: "23:00" },
  { day: "Giovedì", hours: "18:30 - 23:00", isOpen: true, openTime: "18:30", closeTime: "23:00" },
  { day: "Venerdì", hours: "18:30 - 23:30", isOpen: true, openTime: "18:30", closeTime: "23:30" },
  { day: "Sabato", hours: "18:30 - 00:00", isOpen: true, openTime: "18:30", closeTime: "00:00" },
  { day: "Domenica", hours: "18:30 - 23:30", isOpen: true, openTime: "18:30", closeTime: "23:30" },
];

export const REVIEWS = [
  {
    id: "rev1",
    author: "Gianluca M.",
    rating: 5,
    text: "La pizza speciale 'La Gastronomica' è qualcosa di sensazionale. Impasto digeribile a livelli estremi, soffice e croccante nei punti giusti. Consigliatissimo!",
    date: "12 Giu 2026",
  },
  {
    id: "rev2",
    author: "Alessia F.",
    rating: 5,
    text: "Pistacchiosa memorabile! Un sapore incredibilmente delizioso. Il posto è caldo ed accogliente, lo staff delizioso. Un vero punto fermo a San Benedetto.",
    date: "04 Mag 2026",
  },
  {
    id: "rev3",
    author: "Danilo B.",
    rating: 5,
    text: "Le olive ascolane artigianali sono fatte da loro ed hanno un sapore pazzesco, carne saporita e panatura croccante. La birra Collesi freschissima accompagna tutto divinamente.",
    date: "28 Apr 2026",
  },
];
